// tslint:disable max-line-length
export const externalUrls = {
  narrativeAboutWebsite: 'https://about.narrative.org/',
  narrativeSupportCommunity: 'https://community.narrative.org',
  narrativeBlog: 'https://www.narrative.org/p/narrative-blog',
  narrativeTwitter: 'https://twitter.com/narrative_hq',
  narrativeReddit: 'https://www.reddit.com/r/NarrativeNetwork/',
  narrativeTelegram: 'https://t.me/narrativenetwork',
  narrativeFacebook: 'https://www.facebook.com/NarrativeHQ/',
  narrativeLinkedin: 'https://www.linkedin.com/company/narrativehq/',
  narrativeInstagram: 'https://www.instagram.com/narrativenetwork/',
  narrativeCoinMarketCap: 'https://coinmarketcap.com/currencies/narrative/',
  narrativeHowToBuyNrve: 'https://community.narrative.org/support/kb-post/5675216259069241/17363284288612681',
  narrativeHowToBuyANiche: 'https://community.narrative.org/support/kb-post/5675216259069241/15953898400721244',
  narrativeWhatIsCanonicalLink: 'https://community.narrative.org/support/kb-post/5675216259069241/16094635941266103',
  narrativeHowDoIGetAWallet: 'https://community.narrative.org/support/kb-post/5675216259069241/16094635945646080',
  narrativeAup: 'https://about.narrative.org/assets/documents/narrative-acceptable-use-policy.pdf',
  narrativePrivacyPolicy: 'https://about.narrative.org/assets/documents/privacy-policy.pdf',
  narrativeTermsOfService: 'https://about.narrative.org/assets/documents/narrative-tos.pdf',
  narrativeReferralRewards: 'https://community.narrative.org/support/kb-post/5675216259069241/15953898437428580',
  neonWallet: 'https://neonwallet.com',
  latoken: 'https://bit.ly/2zJz1nn',
  switcheo: 'https://switcheo.network/',
  bilaxy: 'https://bilaxy.com/',
  certificationFaq: 'https://community.narrative.org/support/kb-post/5675216259069241/16094635903025835',
  iosGoogleAuthenticator: 'http://appstore.com/googleauthenticator',
  androidGoogleAuthenticator: 'http://play.google.com/store/apps/details?id=com.google.android.apps.authenticator2',
  fathom: 'https://usefathom.com/',
};
