apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: narrative-core
  namespace: dev
spec:
  maxReplicas: 6
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: narrative-core
  targetCPUUtilizationPercentage: 150
