version: '3'
volumes:
    mysql_data: {}
    solr_01_data: {}
    solr_02_data: {}
    solr_03_data: {}
    zk_01_data: {}
    zk_02_data: {}
    zk_03_data: {}
services:
  # this section is for a FULL docker-compose
  # narrative-web-front-end:
  #   image: narrativecompany/narrative-web-front-end:dev-latest
  #   ports:
  #     - 127.0.0.1:81:80
  # narrative-core: 
  #   depends_on:
  #     - mysql
  #     - redis
  #     - solr
  #   environment:
  #     - SPRING_PROFILES_ACTIVE=default,docker,secret
  #     - SPRING_CONFIG_ADDITIONAL-LOCATION=file:./,file:./secret/
  #   image: narrativecompany/narrative-core:kubernetes_class_path_619-39
  #   ports:
  #     - 127.0.0.1:82:8080
  #   volumes:
  #     - ./narrative-core/config/application-docker.properties:/opt/narrative-core/docker/application-cluster.properties
  #     - ./narrative-core/secret/application-secret.properties:/opt/narrative-core/secret/application-secret.properties
  #     - ./narrative-core/config/hibernate-redisson.yaml:/opt/narrative-core/src/main/resources/hibernate-redisson.yaml
  # nginx:
  #   depends_on:
  #     - narrative-web-front-end
  #     - narrative-core
  #   image: nginx
  #   ports:
  #     - 127.0.0.1:80:80
  #   volumes:
  #     - ./nginx/docker.conf:/etc/nginx/conf.d/docker.conf:ro
  mysql:
    image: mysql:5.7
    command: --max_connections=250
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 127.0.0.1:3306:3306
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
      - mysql_data:/var/lib/mysql
  nginx:
    image: nginx
    ports:
      - 127.0.0.1:80:80
      - 127.0.0.1:9090:9090
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  redis:
    #GCP is on a crusty old Redis 3.1 - as close as we can get
    image: redis:3.2
    ports:
      - "127.0.0.1:6379:6379"
  solr-01:
    depends_on:
      - zk-01
      - zk-02
      - zk-03
    environment:
      INIT_SOLR_HOME: "yes"
      SOLR_HOME: /opt/mysolrhome
      SOLR_HOST: solr-01
      SOLR_PORT: 8983
      ZK_HOST: zk-01:2181,zk-02:2181,zk-03:2181
    image: solr:7.4
    ports:
      - 127.0.0.1:8983:8983
    volumes:
      - solr_01_data:/opt/mysolrhome
  solr-02:
    depends_on:
      - zk-01
      - zk-02
      - zk-03
    environment:
      INIT_SOLR_HOME: "yes"
      SOLR_HOME: /opt/mysolrhome
      SOLR_HOST: solr-02
      SOLR_PORT: 8984
      ZK_HOST: zk-01:2181,zk-02:2181,zk-03:2181
    image: solr:7.4
    ports:
      - 127.0.0.1:8984:8984
    volumes:
      - solr_02_data:/opt/mysolrhome
  solr-03:
    depends_on:
      - zk-01
      - zk-02
      - zk-03
    environment:
      INIT_SOLR_HOME: "yes"
      SOLR_HOME: /opt/mysolrhome
      SOLR_HOST: solr-03
      SOLR_PORT: 8985
      ZK_HOST: zk-01:2181,zk-02:2181,zk-03:2181
    image: solr:7.4
    ports:
      - 127.0.0.1:8985:8985
    volumes:
      - solr_03_data:/opt/mysolrhome
  solr-init:
    depends_on:
      - zk-01
      - zk-02
      - zk-03
      - solr-01
    entrypoint: ["/bin/bash", "-c", "/cluster-launcher.sh"]
    environment:
      INIT_SOLR_HOME: "yes"
      SOLR_HOME: /opt/mysolrhome
      ZK_HOST: zk-01:2181,zk-02:2181,zk-03:2181
      SOLR_HOST: solr-01
    image: solr:7
    user: root
    volumes:
      - ../src/solr/config/schema.xml:/opt/configset1/schema.xml
      - ../src/solr/config/solrconfig.xml:/opt/configset1/solrconfig.xml
      - ../src/solr/config/stopwords.txt:/opt/configset1/stopwords.txt
      - ./solr/cluster-launcher.sh:/cluster-launcher.sh
      - solr_01_data:/opt/mysolrhome
  zk-01:
    image: zookeeper:3.5
    hostname: zk-01
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zk-01:2888:3888;2181 server.2=zk-02:2888:3888;2181 server.3=zk-03:2888:3888;2181
    ports:
      - 127.0.0.1:2181:2181
    restart: always
    volumes:
      - zk_01_data:/data
  zk-02:
    image: zookeeper:3.5
    hostname: zk-02
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zk-01:2888:3888;2181 server.2=zk-02:2888:3888;2181 server.3=zk-03:2888:3888;2181
    ports:
      - 127.0.0.1:2182:2181
    restart: always
    volumes:
      - zk_02_data:/data
  zk-03:
    image: zookeeper:3.5
    hostname: zk-03
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zk-01:2888:3888 server.2=zk-02:2888:3888 server.3=zk-03:2888:3888;2181
    ports:
      - 127.0.0.1:2183:2181
    restart: always
    volumes:
      - zk_03_data:/data
