version: '3'
services:
  mysql:
    image: mysql:5.7
    command: --max_connections=250
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 127.0.0.1:3306:3306
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ${HOME}/.narrative/data/mysql:/var/lib/mysql:delegated
  solr:
    entrypoint:
      - /opt/launcher.sh
      - solr-foreground
    image: solr:7.4
    ports:
      - 127.0.0.1:8983:8983
    volumes:
      - ../core/src/solr/config/schema.xml:/opt/narrative/schema.xml
      - ../core/src/solr/config/solrconfig.xml:/opt/narrative/solrconfig.xml
      - ./solr/launcher.sh:/opt/launcher.sh
      - ${HOME}/.narrative/data/solr:/opt/solr/server/solr/narrative:delegated
  redis:
    #GCP is on a crusty old Redis 3.1 - as close as we can get
    image: redis:3.2
    # Enable Redis keyevent events
    command: redis-server --notify-keyspace-events "Exe"
    ports:
      - "6379:6379"
  nginx:
    image: nginx
    ports: 
      - 127.0.0.1:80:80
      - 127.0.0.1:9090:9090
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      
