version: '3'
volumes:
    mysql_data: {}
services:
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_GLOBAL_PASSWORD=XXX
      - MYSQL_UTILITY_PASSWORD=YYY
      - DBPARTITION_SERVER=${DB_SERVER}
    ports:
      - 127.0.0.1:3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
      - ./:/opt/narrative-platform
