apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: downtime-deployment
  name: downtime-deployment
  namespace: ${K8S_ENV}
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: downtime-deployment
      name: downtime-deployment
    spec:
      containers:
      - name: narrative-core
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: default,${K8S_ENV},secret
        - name: SPRING_CONFIG_ADDITIONAL-LOCATION
          value: file:./${K8S_ENV}/,file:./secret/
        image: narrativecompany/narrative-core:${DOCKER_TAG}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: nc
          protocol: TCP
        - containerPort: 8082
          name: cp
          protocol: TCP
        resources:
          requests:
            cpu: .75
            memory: 1024M
          limits:
            cpu: 2
            memory: 2048M
        volumeMounts:
          - name: application-secret-properties
            mountPath: /opt/narrative-core/secret
            readOnly: true
          - name: google-analytics-api-key-json
            mountPath: /opt/narrative-core/google-analytics
            readOnly: true
          - name: application-${K8S_ENV}-properties
            mountPath: /opt/narrative-core/${K8S_ENV}
            readOnly: true
          - name: cloud-storage-credentials
            mountPath: /opt/narrative-core/cloud-storage-credentials
            readOnly: true
      - name: cloud-sql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.13
        command: ["/cloud_sql_proxy",
                  "-term_timeout=30s",
                  "-instances=${GOOGLE_ENV}-narrative:${REGION}:${K8S_ENV}-master=tcp:3306",
                  "-credential_file=/opt/cloud-sql-proxy/${GOOGLE_ENV}-sql.json"]
        resources:
          requests:
            cpu: .25
            memory: 128M
          limits:
            cpu: 1
            memory: 512M
        securityContext:
          runAsUser: 2  # non-root user
          allowPrivilegeEscalation: false
        volumeMounts:
          - name: cloud-sql-proxy
            mountPath: /opt/cloud-sql-proxy
            readOnly: true
      imagePullSecrets:
        - name: narrativecompany-docker
      volumes:
        - name: cloud-sql-proxy
          secret:
            secretName: cloud-sql-proxy
        - name: application-secret-properties
          secret:
            secretName: application-secret-properties
        - name: google-analytics-api-key-json
          secret:
            secretName: google-analytics-api-key-json
        - name: cloud-storage-credentials
          secret:
            secretName: cloud-storage-credentials
        - name: application-${K8S_ENV}-properties
          configMap:
            name: application-${K8S_ENV}-properties
