redisson:
  client:
    scheme: redis
    host: 127.0.0.1
    port: 6379
    threads: 4
    netty-threads: 4
    timeout: 5000
    connect-timeout: 30000

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/reputation?useSSL=false
    username: reputation_user
    password: password

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

