spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/reputation?useSSL=false
    username: reputation_user
    password: password
  jpa:
    database-platform:  org.hibernate.dialect.MySQL57Dialect
    hibernate:
      use-new-id-generator-mappings: true
      naming:
        physical-strategy: org.narrative.shared.hibernate.NarrativePhysicalNamingStrategy