[[CREATE_HIGHBIT_PROC]]
--ADD_HIGHBIT_PROC--

[[INSTALL_USER_REPUTATION_VIEW]]
--CREATE_USER_REPUTATION_VIEW--

[[INSTALL_USER_REPUTATION_HISTORY_VIEW]]
--CREATE_USER_REPUTATION_HISTORY_VIEW--

[[INSTALL_FORMAT_UUID_FUNCTION]]
--ADD_FORMAT_UUID_FUNCTION--