apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: narrative-web-front-end
  name: narrative-web-front-end
  namespace: dev
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: narrative-web-front-end
      name: narrative-web-front-end
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
    spec:
      containers:
      - name: narrative-web-front-end
        image: narrativecompany/narrative-web-front-end:dev-latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: nwfe
          protocol: TCP
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
        resources:
          requests:
            cpu: .25
            memory: 128M
          limits:
            cpu: 1
            memory: 1024M
      imagePullSecrets:
        - name: narrativecompany-docker
