apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: narrative-web-front-end
  namespace: staging
spec:
  maxReplicas: 6
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: narrative-web-front-end
  targetCPUUtilizationPercentage: 150
