############################################################################################################
# Redisson Hibernate (non-local) cache options:
#
#   eviction:
#     max_entries:   max size of cache. Superfluous entries in Redis are evicted using LRU algorithm. 0 value means
#                    unbounded cache. Default value: 0
#   expiration:
#     time_to_live:  time to live per cache entry in Redis. Defined in milliseconds. 0 value means this setting
#                    doesn't affect expiration. Default value: 0
#     max_idle_time: max idle time per cache entry in Redis. Defined in milliseconds. 0 value means this setting
#                    doesn't affect expiration. Default value: 0
#
############################################################################################################

############################################################################################################
# Redisson Hibernate local cache options:
#
#   localcache:
#     size:             max size of local cache. Superfluous entries in Redis are evicted using defined eviction
#                       policy. 0 value means unbounded cache. Default value: 0
#     time_to_live:     time to live per entry in local cache. Defined in milliseconds. 0 value means this setting
#                       doesn't affect expiration. Default value: 0
#     max_idle_time:    max idle time per entry in local cache. Defined in milliseconds. 0 value means this setting
#                       doesn't affect expiration. Default value: 0
#     eviction_policy:
#         NONE          - Cache without eviction.
#         LRU           - Least Recently Used cache.
#         LFU           - Least Frequently Used cache.
#         SOFT          - Cache with Soft Reference used for values. All references will be collected by GC
#         WEAK          - Cache with Weak Reference used for values. All references will be collected by GC
#     reconnection_strategy:  Default value: NONE
#         NONE          - No reconnect handling
#         CLEAR         - Clear local cache if map instance has been disconnected for a while
#         LOAD          - Store invalidated entry hash in invalidation log for 10 minutes. Cache keys
#                         for stored invalidated entry hashes will be removed if LocalCachedMap instance
#                         has been disconnected less than 10 minutes or whole cache will be cleaned otherwise.
#     sync_strategy:    Default value: INVALIDATE
#         NONE          - No synchronizations on map changes.
#         INVALIDATE    - Invalidate cache entry across all LocalCachedMap instances on map entry
#                         change. Broadcasts map entry hash (16 bytes) to all instances.
#         UPDATE        - Update cache entry across all LocalCachedMap instances on map entry change.
#                         Broadcasts full map entry state (Key and Value objects) to all instances.
#     eviction_policy:  Default value: NONE
#         NONE          - Cache without eviction.
#         LRU           - Least Recently Used cache.
#         LFU           - Least Frequently Used cache.
#         SOFT          - Cache with Soft Reference used for values. All references will be collected by GC
#         WEAK          - Cache with Weak Reference used for values. All references will be collected by GC
#
############################################################################################################

# Property name format is the same as in defaults plus the region name - region name is formatted as follows:
# hibernate.<FQCN> ex: hibernate.org.narrative.network.core.area.base.AreaStats

hibernate:
  cache:
    redisson:

      hibernate.org.narrative.network.customizations.narrative.reputation.UserReputation:
        expiration:
          time_to_live: 300000
        localcache:
          time_to_live: 300000