#!/usr/bin/env bash

RESTORE='\033[0m'
RED='\033[00;31m'
GREEN='\033[00;32m'
YELLOW='\033[00;33m'

function errorMessage() {
	echo -e $RED$@$RESTORE
}

function warnMessage() {
	echo -e $YELLOW$@$RESTORE
}

function message() {
	echo -e $GREEN$@$RESTORE
}

function err_report() {
  echo "errexit on line $(caller)" >&2
  popd
  exit -1
}

function askForValue()
{
    prompt=$(message "$1 [$2]: ")
    if [  -z  $3 ]; then
        read -p "$prompt" res
    else
        read -s -p "$prompt" res
    fi;

    echo "${res:-$2}"
}

function promptConfirm() {
  prompt=$(warnMessage "$1 [y/n]: ")
  while true; do
    read -r -n 1 -p "$prompt" REPLY
    case $REPLY in
      [yY]) echo ; return 0 ;;
      [nN]) echo ; return 1 ;;
      *) printf " \033[31m %s \n\033[0m" "invalid input"
    esac
  done
}

trap err_report ERR

